spring:
  datasource:
    url: jdbc:mysql://172.17.91.24:3306/rolex?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=GMT%2B8
    username: admin
    password: GLBFGop0Zh6KF@16E6
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    com.phaeris.rolex: debug