server:
  port: 8080

spring:
  application:
    name: ${spring.profiles.active}-rolex
  profiles:
    active: local
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  quartz:
    # quartz信息存储方式
    job-store-type: jdbc
    # 停机时是否等待任务执行完
    wait-for-jobs-to-complete-on-shutdown: true
    properties:
      org:
        quartz:
          scheduler:
            # 集群配置：自动获取实例id
            instanceId: AUTO
          jobStore:
            class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            # 集群配置：是否开启集群
            isClustered: true
            # 检查集群状态
            clusterCheckinInterval: 3000
            # 获取触发器加锁
            acquireTriggersWithinLock: true
          #线程池配置
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 100
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true

mybatis-plus:
  mapper-locations: classpath:mapper/**/*Mapper.xml
  global-config:
    db-config:
      # 主键类型
      id-type: ASSIGN_ID
      # 全局逻辑删除的实体字段名
      logic-delete-field: deleted
      # 逻辑已删除值
      logic-delete-value: 1
      # 逻辑未删除值
      logic-not-delete-value: 0

management:
  health:
    mail:
      # 关闭邮件健康检查
      enabled: false
  endpoints:
    # web能访问的范围
    web:
      exposure:
        include: "*"
    # 默认是否开启（必须要配置了web能访问的范围开启关闭才有效）
    enabled-by-default: false
  # 开启的端点，按需打开（语法management.endpoint.端点.enabled=true）
  endpoint:
    loggers:
      enabled: true
    health:
      enabled: true

logging:
  level:
    root: info